// <auto-generated />
using System;
using EvidencijaNezaposlenih.Repozitorijum.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidencijaNezaposlenih.Repozitorijum.Migrations
{
    [DbContext(typeof(EvidencijaNezaposlenihDBContext))]
    [Migration("20240517144156_edit")]
    partial class edit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidencijaNezaposlenih.ModeliPodataka.Modeli.Nezaposleni", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Nezaposleni");
                });

            modelBuilder.Entity("EvidencijaNezaposlenih.ModeliPodataka.Modeli.Poslodavac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PIB")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Poslodavci");
                });

            modelBuilder.Entity("EvidencijaNezaposlenih.ModeliPodataka.Modeli.RadniOdnos", b =>
                {
                    b.Property<int>("PIB")
                        .HasColumnType("int");

                    b.Property<string>("NezaposleniID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.HasKey("PIB", "NezaposleniID");

                    b.HasIndex("NezaposleniID");

                    b.ToTable("RadniOdnosi");
                });

            modelBuilder.Entity("EvidencijaNezaposlenih.ModeliPodataka.Modeli.RadniOdnos", b =>
                {
                    b.HasOne("EvidencijaNezaposlenih.ModeliPodataka.Modeli.Nezaposleni", "Nezaposleni")
                        .WithMany("RadniOdnos")
                        .HasForeignKey("NezaposleniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidencijaNezaposlenih.ModeliPodataka.Modeli.Poslodavac", "Poslodavac")
                        .WithMany()
                        .HasForeignKey("PIB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nezaposleni");

                    b.Navigation("Poslodavac");
                });

            modelBuilder.Entity("EvidencijaNezaposlenih.ModeliPodataka.Modeli.Nezaposleni", b =>
                {
                    b.Navigation("RadniOdnos");
                });
#pragma warning restore 612, 618
        }
    }
}
